feature:
  - changed-files:
      - any-glob-to-any-file:
          - 'app/**'
          - 'hometube/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'README.md'
          - 'docs/**'

test:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'

perf:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.py'

chore:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '.devcontainer/**'

deps:
  - changed-files:
      - any-glob-to-any-file:
          - 'pyproject.toml'
          - 'uv.lock'
          - 'requirements/**'

docker:
  - changed-files:
      - any-glob-to-any-file:
          - 'Dockerfile'
          - 'docker-compose*.yml'
          - '.dockerignore'

config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.env*'
          - '*.ini'
          - '*.toml'
          - '*.yaml'
          - '*.yml'

ui:
  - changed-files:
      - any-glob-to-any-file:
          - 'app/translations/**'
          - 'app/main.py'

scripts:
  - changed-files:
      - any-glob-to-any-file:
          - 'scripts/**'
          - '*.sh'